### ISSUE TITLE
Support "derived" peripherals

### ISSUE THREAD

**Issue by ehntoo** [Vector35/svdmap#3]
The SVD spec allows for peripherals within an SVD to "derive" their definition from other peripherals in the same document. Derived peripherals inherit registers and properties from the peripheral they derive from, but allow overriding elements as well.

This feature is relatively common in SVDs in the field. You can find some examples at the following links:
https://github.com/py32-rs/py32-data/blob/9ca9b860b458723b802df73223ce051f89d6e33a/svd/PY32F030xx.svd
https://github.com/ch32-rs/ch32-rs/blob/10340a2d9f74789279d00610cdb71d8b11d89c1f/svd/fixed/ch32v30x.svd

**Comment by emesare** [comment]
Should be done now, thanks for the report https://github.com/Vector35/svdmap/commit/3c672d8fb18c9512533c3d69b5f0cd1d18b6a488

**Comment by emesare** [comment]
Right now the derived types will be separated, if this is not desired let me know and I can re-open and we can discuss further. I am also on the binary ninja slack (mason@vector35.com)
